from typing import List, Literal, Optional
from pydantic import BaseModel, Field, PrivateAttr
from typing import Any, Dict, List, Optional

class ResearchClaim(BaseModel):
    claim: str
    source_title: str
    source_url: str
    evidence: str
    importance: Literal["LOW", "MEDIUM", "HIGH"]
    claim_type: Literal[
        "FACT",
        "STATISTIC",
        "FINDING",
        "OPINION",
        "PREDICTION",
        "RECOMMENDATION",
    ]

class ResearchReport(BaseModel):
    title: str
    executive_summary: str
    research_question: str
    key_findings: List[str] = Field(default_factory=list)
    evidence_analysis: str
    contradictory_findings: List[str] = Field(default_factory=list)
    limitations: List[str] = Field(default_factory=list)
    conclusion: str
    references: List[str] = Field(default_factory=list)


class ClaimExtractionResult(BaseModel):
    claims: List[ResearchClaim] = Field(
        default_factory=list
    )


class ResearchCritique(BaseModel):
    overall_status: Literal["PASS", "REVISE"]
    factual_issues: List[str] = Field(default_factory=list)
    unsupported_claims: List[str] = Field(default_factory=list)
    missing_citations: List[str] = Field(default_factory=list)
    contradiction_issues: List[str] = Field(default_factory=list)
    coverage_issues: List[str] = Field(default_factory=list)
    clarity_issues: List[str] = Field(default_factory=list)
    recommendations: List[str] = Field(default_factory=list)

class ResearchPlan(BaseModel):
    """
    Structured plan generated by the Supervisor Agent.
    """
    research_goal: str = Field(description="Main objective of the research")
    sub_questions: List[str] = Field(
        default_factory=list,
        description="Important sub-questions that need to be answered"
    )
    search_queries: List[str] = Field(
        default_factory=list,
        description="Search queries used to investigate the topic"
    )
    source_types: List[str] = Field(
        default_factory=list,
        description="Useful source types for the research"
    )

class SearchResult(BaseModel):
    """
    A single search result returned by Tavily.
    """
    title: str
    url: str
    snippet: str

class ResearchSource(BaseModel):
    """
    A source selected for deeper research.
    """
    title: str
    url: str
    content: str = ""
    source_type: str = "unknown"


class SourceEvaluation(BaseModel):
    title: str
    url: str
    source_type: str
    relevance_score: float = Field(ge=0, le=1)
    authority_score: float = Field(ge=0, le=1)
    recency_score: float = Field(ge=0,le=1)
    evidence_quality_score: float = Field(ge=0, le=1)
    overall_score: float = Field(ge=0, le=1)
    strengths: List[str] = Field(default_factory=list)
    weaknesses: List[str] = Field(default_factory=list)

class FactCheck(BaseModel):
    claim: str
    status: Literal[
        "SUPPORTED",
        "PARTIALLY_SUPPORTED",
        "CONTRADICTED",
        "UNVERIFIED"
    ]
    confidence: float = Field(ge=0, le=1)
    explanation: str
    supporting_sources: List[str] = Field(default_factory=list)
    contradicting_sources: List[str] = Field(default_factory=list)

class Contradiction(BaseModel):
    topic: str
    claim_a: str
    source_a: str
    claim_b: str
    source_b: str
    explanation: str
    severity: Literal[
        "LOW",
        "MEDIUM",
        "HIGH"
    ]


class Citation(BaseModel):
    claim: str
    source_title: str
    source_url: str
    supporting_evidence: str

class EvidencePackage(BaseModel):
    source_evaluations: List[SourceEvaluation] = Field(
        default_factory=list
    )

    fact_checks: List[FactCheck] = Field(
        default_factory=list
    )

    contradictions: List[Contradiction] = Field(
        default_factory=list
    )

    citations: List[Citation] = Field(
        default_factory=list
    )

class ResearchTraceEvent(BaseModel):
    timestamp: str
    stage: str
    event: str
    details: Dict[str, Any] = Field(default_factory=dict)

class ResearchState(BaseModel):
    topic: str = ""
    research_plan: Optional[ResearchPlan] = None
    search_results: List[SearchResult] = Field(default_factory=list)
    sources: List[ResearchSource] = Field(default_factory=list)
    scraped_content: str = ""
    evidence: EvidencePackage = Field(default_factory=EvidencePackage)
    report: Optional[ResearchReport] = None
    feedback: str = ""
    status: str = "initialized"
    errors: List[str] = Field(default_factory=list)
    trace: List[ResearchTraceEvent] = Field(default_factory=list)
    _claims: List[ResearchClaim] = PrivateAttr(default_factory=list)
    _coverage: Dict[str, Any] = PrivateAttr(default_factory=dict)
    _memory_results: List[Any] = PrivateAttr(default_factory=list)
    _memory_context: str = PrivateAttr(default="")